# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Track Vim plugins defined in configs/1.plugins.vim
  # Dependabot doesn’t natively parse vim-plug, but you can make it check for
  # new commits or releases in plugin repos by listing them manually.
  # Add or remove any you want it to track automatically.
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"

  # (Optional) Track JS dependencies (Markdown Preview plugin uses yarn)
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
