# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh
set -g set-clipboard on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# Theme flavor
set -g @catppuccin_flavor 'mocha' # Available: latte, frappe, macchiato, mocha
set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none

# Some basic mocha colors.
set -g @ctp_bg "#24273a"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_fg "#cad3f5"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_crust "#181926"

# Make the status line pretty and add some modules
set -gF status-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-left "#{E:@catppuccin_status_date_time}"

set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

set-option -a terminal-features 'tmux-256color:RGB'

run '~/.tmux/plugins/tpm/tpm'

